CREATE TABLE IF NOT EXISTS projects(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId integer REFERENCES projects(id)
);

INSERT INTO projects(name,priority,description,deliverydate)
    VALUES('Jhonny',1,'Usando java','2019-05-12')

INSERT INTO projects(name,priority,description,deliverydate)
    VALUES('Juan',2,'Usando python','2020-05-12')

INSERT INTO projects(name,priority,description,deliverydate)
    VALUES('Maria',2,'Usando dart','2020-05-12')


-- INSERT TASKS DATA

INSERT INTO tasks(name,done,projectId)
    VALUES('Web master',true,1);
INSERT INTO tasks(name,done,projectId)
    VALUES('Desarrollador',true,2);
INSERT INTO tasks(name,done,projectId)
    VALUES('Desarrollador front',false,2)
INSERT INTO tasks(name,done,projectId)
    VALUES('Desarrollador back',true,3)